const $=s=>document.querySelector(s),cfg=window.KDROID_CONFIG;let token=sessionStorage.getItem('kdroid_token')||'';
function notice(m,e=false){const n=$('#notice');n.textContent=m;n.className='show'+(e?' error':'');clearTimeout(notice.t);notice.t=setTimeout(()=>n.className='',4000)}
async function request(path,opt={}){const h={apikey:cfg.publishableKey,'Content-Type':'application/json',...(opt.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(cfg.supabaseUrl+path,{...opt,headers:h});let b=null;try{b=await r.json()}catch{}if(!r.ok)throw new Error(b?.message||b?.error_description||`Request failed (${r.status})`);return b}
async function login(e){e.preventDefault();try{const b=await request('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});token=b.access_token;sessionStorage.setItem('kdroid_token',token);show();notice('Signed in')}catch(x){notice(x.message,true)}}
function check(text,value,disabled=false){const l=document.createElement('label'),i=document.createElement('input');l.className='check';i.type='checkbox';i.checked=value;i.disabled=disabled;l.append(i,document.createTextNode(text));return{l,i}}
function render(d){const a=document.createElement('article');a.className='device';const h=document.createElement('h3');h.textContent=d.name||'KDroid phone';const m=document.createElement('div');m.className='meta';m.textContent=`${d.model||'Unknown model'} | ${d.public_id}`;const seen=document.createElement('small');seen.textContent='Last connected: '+(d.last_seen_at?new Date(d.last_seen_at).toLocaleString():'Never');const c=document.createElement('div');c.className='controls';const basic=check('Basic',true,true),shop=check('Shopping',!!d.shopping_enabled),biz=check('Business',!!d.business_enabled),save=document.createElement('button');save.textContent='Save access';c.append(basic.l,shop.l,biz.l,save);save.onclick=async()=>{try{await request(`/rest/v1/kdroid_devices?id=eq.${d.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({basic_enabled:true,shopping_enabled:shop.i.checked,business_enabled:biz.i.checked})});await command(d.id,'sync_catalog');notice(`${h.textContent} will sync`)}catch(x){notice(x.message,true)}};const f=document.createElement('form'),p=document.createElement('input'),send=document.createElement('button');f.className='command';p.placeholder='App package, e.g. com.example.app';p.required=true;send.textContent='Send update';f.append(p,send);f.onsubmit=async e=>{e.preventDefault();try{await command(d.id,'update_app',p.value.trim());p.value='';notice(`Update queued for ${h.textContent}`)}catch(x){notice(x.message,true)}};a.append(h,m,seen,c,f);return a}
async function loadApps(){const box=$("#apps");try{const r=await fetch("/catalog/v1/catalog.json",{cache:"no-store"});if(!r.ok)throw new Error("Catalog unavailable");const catalog=await r.json(),apps=catalog.apps.filter(a=>!a.hidden);$("#app-count").textContent=`${apps.length} apps`;box.replaceChildren();apps.forEach(app=>{const card=document.createElement("article"),icon=document.createElement("img"),body=document.createElement("div"),name=document.createElement("h3"),meta=document.createElement("small"),link=document.createElement("a");card.className="app";icon.src=app.iconUrl||"";icon.alt="";icon.loading="lazy";name.textContent=app.name;meta.textContent=`${app.versionName} | ${app.store}`;body.append(name,meta);link.href=app.apkFiles[0].url;link.textContent="Download";link.rel="noopener";card.append(icon,body,link);box.append(card)})}catch(e){$("#app-count").textContent="Unavailable";box.textContent=e.message}}
async function command(id,type,pkg=null){const row={device_id:id,command_type:type,payload:{}};if(pkg)row.package_name=pkg;await request('/rest/v1/kdroid_commands',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(row)})}
async function load(){const box=$('#devices');box.textContent='Loading...';try{const rows=await request('/rest/v1/kdroid_devices?select=*&order=enrolled_at.desc');box.replaceChildren();if(!rows.length){box.innerHTML='<p class="empty">No phones enrolled yet.</p>';return}rows.forEach(d=>box.append(render(d)))}catch(x){if(/jwt|permission|401/i.test(x.message))signout();else{box.textContent='';notice(x.message,true)}}}
function show(){$('#auth').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#logout').classList.remove('hidden');load()}function signout(){token='';sessionStorage.removeItem('kdroid_token');$('#auth').classList.remove('hidden');$('#dashboard').classList.add('hidden');$('#logout').classList.add('hidden')}
$('#login').addEventListener('submit',login);$('#logout').onclick=signout;$('#refresh').onclick=load;loadApps();if(token)show();
